Component.create(brand: "Onkyo", name: "TXNR809", price: 60000, category: "receiver")
Component.create(brand: "Marantz", name: "SR7008", price: 90000, category: "receiver")
Component.create(brand: "Odyssey Audio", name: "Lorelei", price: 200000, category: "speaker")
Component.create(brand: "NHT", name: "Classic Series", price: 200000, category: "speaker")
Component.create(brand: "Cambridge", name: "Azur 651C", price: 15000, category: "media_player")
Component.create(brand: "Apple", name: "iPhone", price: 600, category: "media_player")
